pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Checkout GIT') {
            steps {
                echo 'Pulling... ';
                    git branch: 'Ahmed',
                        url : 'https://github.com/louatisahar/DevOps',
                        credentialsId: '08c643de-905d-45a9-9d2f-3f709ad04201';
            }
        }
        stage('Testing maven') {
            steps {
                sh """mvn -v"""
            }
        }
        
        
    }
}
